language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"


# install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install coveralls
  - pip install coverage
  - wget ftp://emboss.open-bio.org/pub/EMBOSS/emboss-latest.tar.gz -O /tmp/emboss.tar.gz
  - tar -xvzf /tmp/emboss.tar.gz
  - cd EMBOSS-6.6.0
  - ./configure --without-x
  - make
  - cd ..
  - export PATH=$PATH:$PWD/EMBOSS-6.6.0/emboss
  #install ORFm
  - wget https://github.com/wwood/OrfM/releases/download/v0.7.1/orfm-0.7.1_Linux_x86_64.tar.gz -O /tmp/orfm.tar.gz
  - tar -xvzf /tmp/orfm.tar.gz
  - export PATH=$PATH:$PWD/orfm-0.7.1_Linux_x86_64
  
  
# command to run tests
script:
  - ls
  #run getorf comparison
  - getorf -find 3 -outseq ec3.fa -sequence tests/testseq/ecoli.fa -min 120
  - getorf -find 1 -outseq ecp3.fa -sequence tests/testseq/ecoli.fa -min 120
  - getorf -find 2 -outseq ec.fa -sequence tests/testseq/ecoli.fa -min 120
  - getorf -find 0 -outseq ecp.fa -sequence tests/testseq/ecoli.fa -min 120
  - orfipy --single --partial-3 --start ATG --min 120 --outdir ofout --dna d3 --pep p3 tests/testseq/ecoli.fa
  - orfipy --single --between-stops --min 120 --outdir ofout --dna d --pep p tests/testseq/ecoli.fa
  - python scripts/compare_fasta_files.py ec3.fa ofout/d3
  - python scripts/compare_fasta_files.py ecp3.fa ofout/p3
  - python scripts/compare_fasta_files.py ec.fa ofout/d
  - python scripts/compare_fasta_files.py ecp.fa ofout/p
  #test run some parameters
  - orfipy --single --between-stops --min 120 --outdir ofout --dna d --pep p tests/testseq/ecoli.fa --include-stop
  - orfipy --single --min 120 --outdir ofout --dna d --pep p tests/testseq/ecoli.fa --include-stop --partial-3 --partial-5
  - orfipy --single --min 120 --outdir ofout --dna d --pep p tests/testseq/ecoli.fa --include-stop --partial-5
  - orfipy --single --min 120 --outdir ofout --dna d --pep p tests/testseq/ecoli.fa --include-stop --partial-5 --start ACG --stop TGC
  #test gzipped
  - gzip tests/testseq/ecoli.fa
  - orfipy --single --partial-3 --start ATG --min 120 --outdir ofout --dna d3 --pep p3 tests/testseq/ecoli.fa.gz
  - orfipy --single --between-stops --min 120 --outdir ofout --dna d --pep p tests/testseq/ecoli.fa.gz
  - python scripts/compare_fasta_files.py ec3.fa ofout/d3
  - python scripts/compare_fasta_files.py ecp3.fa ofout/p3
  - python scripts/compare_fasta_files.py ec.fa ofout/d
  - python scripts/compare_fasta_files.py ecp.fa ofout/p
  #test fq
  - orfipy --single --between-stops --min 36 --outdir fqout --dna d --pep p tests/testseq/sample.fq
  - orfm -m 36 -t orfm_dna tests/testseq/sample.fq > orfm_pep
  - python scripts/compare_fasta_files.py orfm_dna fqout/d
  - python scripts/compare_fasta_files.py orfm_pep fqout/p
  #test fq.gzip
  - gzip tests/testseq/sample.fq
  - orfipy --single --between-stops --min 36 --outdir fqoutgz --dna d --pep p tests/testseq/sample.fq.gz
  - python scripts/compare_fasta_files.py orfm_dna fqoutgz/d
  - python scripts/compare_fasta_files.py orfm_pep fqoutgz/p

  #see logs
  - cat ofout/*.log
  #- coverage run -m pytest tests/
  #- coverage report --show-missing  
#after_success:
#  - coveralls
