language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"


# install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install coveralls
  - pip install coverage
  - wget ftp://emboss.open-bio.org/pub/EMBOSS/emboss-latest.tar.gz -O /tmp/emboss.tar.gz
  - tar -xvzf /tmp/emboss.tar.gz
  
  
# command to run tests
script:
  - ls
  - coverage run -m pytest tests/
  - coverage report --show-missing  
after_success:
  - coveralls
